# Generated by Django 5.1.5 on 2025-02-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
