# Generated by Django 5.1.5 on 2025-02-20 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')])),
                ('would_recommend', models.IntegerField(choices=[(1, 'Definitely Not'), (2, 'Probably Not'), (3, 'Maybe'), (4, 'Probably Yes'), (5, 'Definitely Yes')])),
                ('favorite_feature', models.CharField(max_length=100)),
                ('most_challenging', models.CharField(max_length=100)),
                ('feature_requests', models.TextField()),
                ('improvement_suggestions', models.TextField()),
                ('learning_goals', models.TextField()),
                ('interface_rating', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
