# Generated by Django 5.1.5 on 2025-02-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_subscription'),
        ('api', '0011_create_default_subscription_plans'),
    ]

    operations = [
    ]
