# Generated by Django 5.1.5 on 2025-03-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcontent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.language'),
        ),
        migrations.AddIndex(
            model_name='readingcontent',
            index=models.Index(fields=['language'], name='api_reading_languag_ac7904_idx'),
        ),
        migrations.AddIndex(
            model_name='readingcontent',
            index=models.Index(fields=['language', 'level'], name='api_reading_languag_18925d_idx'),
        ),
    ]
