# Generated by Django 5.1.5 on 2025-03-11 00:01

from django.db import migrations

def update_subscriptions(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    UserProfile.objects.filter(subscription__isnull=True).update(subscription_id=1)

def reverse_subscriptions(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    UserProfile.objects.filter(subscription_id=1).update(subscription=None)

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0018_update_words_count'),
    ]

    operations = [
        migrations.RunPython(update_subscriptions, reverse_subscriptions),
    ]
